name: WellWhaddyaKnow
options:
  bundleIdPrefix: com.daylily
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: false
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_STYLE: Automatic

packages:
  WellWhaddyaKnow:
    path: .

targets:
  WellWhaddyaKnow:
    type: application
    platform: macOS
    sources:
      - path: Sources/WellWhaddyaKnowApp
        excludes:
          - "*.entitlements"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.daylily.wellwhaddyaknow
        INFOPLIST_FILE: Sources/WellWhaddyaKnowApp/Info.plist
        CODE_SIGN_ENTITLEMENTS: Sources/WellWhaddyaKnowApp/WellWhaddyaKnow.entitlements
        PRODUCT_NAME: WellWhaddyaKnow
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
    dependencies:
      - package: WellWhaddyaKnow
        product: XPCProtocol
      - package: WellWhaddyaKnow
        product: Reporting
      - package: WellWhaddyaKnow
        product: Timeline
      - package: WellWhaddyaKnow
        product: CoreModel
      - package: WellWhaddyaKnow
        product: Storage
    entitlements:
      path: Sources/WellWhaddyaKnowApp/WellWhaddyaKnow.entitlements

schemes:
  WellWhaddyaKnow:
    build:
      targets:
        WellWhaddyaKnow: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

