# Homebrew formula for WellWhaddyaKnow — CLI, agent, and GUI
# To install: brew tap Daylily-Informatics/tap && brew install wwk

class Wwk < Formula
  desc "macOS time tracker — CLI, background agent, and menu bar app"
  homepage "https://github.com/Daylily-Informatics/well-whaddya-know"
  url "https://github.com/Daylily-Informatics/well-whaddya-know/archive/refs/tags/0.11.0.tar.gz"
  sha256 "2939fd9308cafc1a01455bf2dae12effddfd3e60f2348ee59b1cd6d756ed851d"
  license "MIT"
  head "https://github.com/Daylily-Informatics/well-whaddya-know.git", branch: "main"

  depends_on xcode: ["14.0", :build]
  depends_on :macos

  def install
    # Overwrite BuildVersion.swift with the formula version
    mkdir_p "Sources/Shared/CoreModel"
    rm_f "Sources/Shared/CoreModel/BuildVersion.swift"
    (buildpath/"Sources/Shared/CoreModel/BuildVersion.swift").write <<~SWIFT
      // BuildVersion.swift — generated by Homebrew formula
      public enum BuildVersion {
          public static let version: String = "#{version}"
      }
    SWIFT

    # Construct paths for the app bundle up front so the shell
    # script can install binaries directly to their final locations.
    app_bundle = prefix/"WellWhaddyaKnow.app"
    contents   = app_bundle/"Contents"
    macos_dir  = contents/"MacOS"
    resources  = contents/"Resources"
    la_dir     = contents/"Library/LaunchAgents"

    bin.mkpath
    macos_dir.mkpath
    resources.mkpath
    la_dir.mkpath

    # Swift 6 new build system may remove previous binaries when
    # building a different --product.  Build each product and install
    # immediately within a single shell invocation.
    system "sh", "-c", <<~SH
      set -e
      FLAGS="--configuration release --disable-sandbox -Xswiftc -cross-module-optimization"

      swift build $FLAGS --product wwk
      BP=$(swift build --show-bin-path --configuration release)
      install -m 755 "$BP/wwk" "#{bin}/"

      swift build $FLAGS --product wwkd
      install -m 755 "$BP/wwkd" "#{bin}/"
      install -m 755 "$BP/wwkd" "#{macos_dir}/"

      swift build $FLAGS --product WellWhaddyaKnow
      install -m 755 "$BP/WellWhaddyaKnow" "#{macos_dir}/"

      echo "--- installed ---"
      ls -la "#{bin}/wwk" "#{bin}/wwkd" "#{macos_dir}/WellWhaddyaKnow" "#{macos_dir}/wwkd"
    SH

    # Embed launchd plist (required for SMAppService)
    cp "Sources/WellWhaddyaKnowApp/LaunchAgents/com.daylily.wellwhaddyaknow.agent.plist",
       la_dir/"com.daylily.wellwhaddyaknow.agent.plist"

    # Process Info.plist — substitute Xcode variables
    info_plist = (buildpath/"Sources/WellWhaddyaKnowApp/Info.plist").read
    info_plist.gsub!("$(EXECUTABLE_NAME)", "WellWhaddyaKnow")
    info_plist.gsub!("$(PRODUCT_BUNDLE_IDENTIFIER)", "com.daylily.wellwhaddyaknow")
    (contents/"Info.plist").write(info_plist)

    cp "Sources/WellWhaddyaKnowApp/PrivacyInfo.xcprivacy", resources/"PrivacyInfo.xcprivacy"
    (contents/"PkgInfo").write("APPL????")

    # Ad-hoc codesign (inner → outer)
    system "codesign", "--force", "--sign", "-",
           "-i", "com.daylily.wellwhaddyaknow.agent",
           macos_dir/"wwkd"
    system "codesign", "--force", "--sign", "-",
           macos_dir/"WellWhaddyaKnow"
    system "codesign", "--force", "--sign", "-",
           app_bundle.to_s
  end

  def caveats
    <<~EOS
      WellWhaddyaKnow — macOS time tracker (CLI + agent + GUI).

      Quick start:
        wwk agent install     # Register agent as login item
        wwk gui               # Launch the menu bar app
        wwk status            # Show current tracking status

      Agent management:
        wwk agent status      # Check agent status
        wwk agent start       # Start the agent
        wwk agent stop        # Stop the agent
        wwk agent uninstall   # Remove login item

      Reporting:
        wwk today             # Today's summary
        wwk week              # This week's summary
        wwk --help            # Full command reference

      GUI app location:
        #{opt_prefix}/WellWhaddyaKnow.app
    EOS
  end

  test do
    assert_match "USAGE: wwk", shell_output("#{bin}/wwk --help")
    assert_match "gui", shell_output("#{bin}/wwk --help")
  end
end

