# Homebrew formula for wwk CLI
# To install: brew tap Daylily-Informatics/tap && brew install wwk

class Wwk < Formula
  desc "CLI for WellWhaddyaKnow time tracker"
  homepage "https://github.com/Daylily-Informatics/well-whaddya-know"
  url "https://github.com/Daylily-Informatics/well-whaddya-know/archive/refs/tags/0.5.1.tar.gz"
  sha256 "27ac14bceb343ecbd97b3d1a48011097aac7685a52a0c801d0b48ab3a419d1cb"
  license "MIT"
  head "https://github.com/Daylily-Informatics/well-whaddya-know.git", branch: "main"

  depends_on xcode: ["14.0", :build]
  depends_on :macos

  def install
    # Generate BuildVersion.swift with the formula version
    # (source tarballs may not contain .git, so generate-version.sh would fall back)
    mkdir_p "Sources/Shared/CoreModel"
    (buildpath/"Sources/Shared/CoreModel/BuildVersion.swift").write <<~SWIFT
      // BuildVersion.swift — generated by Homebrew formula
      public enum BuildVersion {
          public static let version: String = "#{version}"
      }
    SWIFT

    system "swift", "build",
           "--configuration", "release",
           "--disable-sandbox",
           "-Xswiftc", "-cross-module-optimization"
    bin.install ".build/release/wwk"
    bin.install ".build/release/wwkd"
  end

  def caveats
    <<~EOS
      wwk is the CLI and wwkd is the background agent for WellWhaddyaKnow.

      Start the agent:
        wwkd &

      Usage:
        wwk status          # Show current status
        wwk today           # Today's summary
        wwk week            # This week's summary
        wwk --help          # Full command reference

      For the menu bar UI, build WellWhaddyaKnow.app from source:
        git clone https://github.com/Daylily-Informatics/well-whaddya-know.git
        cd well-whaddya-know && bash scripts/build-app.sh --release
        open .build/release/WellWhaddyaKnow.app
    EOS
  end

  test do
    # Test that the CLI runs and shows help
    assert_match "USAGE: wwk", shell_output("#{bin}/wwk --help")
  end
end

