# Homebrew formula for WellWhaddyaKnow — CLI, agent, and GUI
# To install: brew tap Daylily-Informatics/tap && brew install wwk

class Wwk < Formula
  desc "macOS time tracker — CLI, background agent, and menu bar app"
  homepage "https://github.com/Daylily-Informatics/well-whaddya-know"
  url "https://github.com/Daylily-Informatics/well-whaddya-know/archive/refs/tags/0.6.0.tar.gz"
  sha256 "5b7acd96ce23f31a8f13f11b4f8a6077669c55be36363985df065784e834bfe5"
  license "MIT"
  head "https://github.com/Daylily-Informatics/well-whaddya-know.git", branch: "main"

  depends_on xcode: ["14.0", :build]
  depends_on :macos

  def install
    # Overwrite BuildVersion.swift with the formula version
    mkdir_p "Sources/Shared/CoreModel"
    rm_f "Sources/Shared/CoreModel/BuildVersion.swift"
    (buildpath/"Sources/Shared/CoreModel/BuildVersion.swift").write <<~SWIFT
      // BuildVersion.swift — generated by Homebrew formula
      public enum BuildVersion {
          public static let version: String = "#{version}"
      }
    SWIFT

    # Build all products (wwk, wwkd, WellWhaddyaKnow)
    system "swift", "build",
           "--configuration", "release",
           "--disable-sandbox",
           "-Xswiftc", "-cross-module-optimization"

    # Install CLI and agent binaries
    bin.install ".build/release/wwk"
    bin.install ".build/release/wwkd"

    # Construct WellWhaddyaKnow.app bundle
    app_bundle = prefix/"WellWhaddyaKnow.app"
    contents   = app_bundle/"Contents"
    macos_dir  = contents/"MacOS"
    resources  = contents/"Resources"
    la_dir     = contents/"Library/LaunchAgents"

    macos_dir.mkpath
    resources.mkpath
    la_dir.mkpath

    cp ".build/release/WellWhaddyaKnow", macos_dir/"WellWhaddyaKnow"
    cp ".build/release/wwkd",            macos_dir/"wwkd"

    # Embed launchd plist (required for SMAppService)
    cp "Sources/WellWhaddyaKnowApp/LaunchAgents/com.daylily.wellwhaddyaknow.agent.plist",
       la_dir/"com.daylily.wellwhaddyaknow.agent.plist"

    # Process Info.plist — substitute Xcode variables
    info_plist = (buildpath/"Sources/WellWhaddyaKnowApp/Info.plist").read
    info_plist.gsub!("$(EXECUTABLE_NAME)", "WellWhaddyaKnow")
    info_plist.gsub!("$(PRODUCT_BUNDLE_IDENTIFIER)", "com.daylily.wellwhaddyaknow")
    (contents/"Info.plist").write(info_plist)

    cp "Sources/WellWhaddyaKnowApp/PrivacyInfo.xcprivacy", resources/"PrivacyInfo.xcprivacy"
    (contents/"PkgInfo").write("APPL????")

    # Ad-hoc codesign (inner → outer)
    system "codesign", "--force", "--sign", "-",
           "-i", "com.daylily.wellwhaddyaknow.agent",
           macos_dir/"wwkd"
    system "codesign", "--force", "--sign", "-",
           macos_dir/"WellWhaddyaKnow"
    system "codesign", "--force", "--sign", "-",
           app_bundle.to_s
  end

  def caveats
    <<~EOS
      WellWhaddyaKnow — macOS time tracker (CLI + agent + GUI).

      Quick start:
        wwk agent install     # Register agent as login item
        wwk gui               # Launch the menu bar app
        wwk status            # Show current tracking status

      Agent management:
        wwk agent status      # Check agent status
        wwk agent start       # Start the agent
        wwk agent stop        # Stop the agent
        wwk agent uninstall   # Remove login item

      Reporting:
        wwk today             # Today's summary
        wwk week              # This week's summary
        wwk --help            # Full command reference

      GUI app location:
        #{opt_prefix}/WellWhaddyaKnow.app
    EOS
  end

  test do
    assert_match "USAGE: wwk", shell_output("#{bin}/wwk --help")
    assert_match "gui", shell_output("#{bin}/wwk --help")
  end
end

