#!/bin/sh
# generate-version.sh — Derive version from git tags and write BuildVersion.swift
# Usage: ./scripts/generate-version.sh [PROJECT_ROOT]
#
# Produces: Sources/Shared/CoreModel/BuildVersion.swift
# This file is .gitignored and regenerated on every build.

set -e

PROJECT_ROOT="${1:-$(cd "$(dirname "$0")/.." && pwd)}"
OUTPUT="$PROJECT_ROOT/Sources/Shared/CoreModel/BuildVersion.swift"

# Try git describe; fall back gracefully
if command -v git >/dev/null 2>&1 && git -C "$PROJECT_ROOT" rev-parse --git-dir >/dev/null 2>&1; then
    # --tags: consider all tags, not just annotated
    # --always: fall back to abbreviated commit hash if no tags
    VERSION=$(git -C "$PROJECT_ROOT" describe --tags --always 2>/dev/null || echo "0.0.0-unknown")
else
    VERSION="0.0.0-unknown"
fi

# Strip leading 'v' if present (our tags don't use it, but be safe)
VERSION="${VERSION#v}"

cat > "$OUTPUT" << EOF
// BuildVersion.swift — AUTO-GENERATED by scripts/generate-version.sh
// Do not edit manually. Regenerated on every build.

public enum BuildVersion {
    /// Semantic version derived from \`git describe --tags --always\`.
    /// Format: "X.Y.Z" on exact tag, "X.Y.Z-N-gHASH" between tags.
    public static let version: String = "$VERSION"
}
EOF

echo "BuildVersion: $VERSION -> $OUTPUT"

